Решение 2 и 3 главы
js-tasks-ru/jsbasic-20230629_andrei-verbitskiy pull request #3
Opened 2023-07-18 10:17 UTC by AndreiVerbitski

2023-07-18 10:18 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-07-22 19:25 UTC, SinimaWath requested changes

2023-07-22 19:25 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  })
Давай тут используем `map`, и без временной переменной result

2023-07-22 19:25 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  return result
Сразу можно вернуть результат: `return arr.filter(x => arr[x] >= a && arr[x] <= b)`

2023-07-22 19:25 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  })
Давай эту конструкцию заменим на: `users.filter().map()`

2023-07-22 19:25 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  })
Весь этот код стоит заменить на 3 операции:
```
users.filter().map().join('\n')
```

join('\n') - чтобы добавить переносы

2023-07-22 19:25 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  return result
Давай сразу вернем результат без временных переменных:
```
return {
  min: newArr[0],
  max:  newArr[newArr.length - 1]
}
```

2023-07-31 19:20 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-08-02 16:44 UTC, SinimaWath approved these changes

2023-08-02 16:45 UTC, merged